extends: existence
message: "Don't use internet slang aabreviations such as '%s'."
link: 'https://developers.google.com/style/aabreviations'
ignorecase: true
level: error
tokens:
  - 'tl;dr'
  - ymmv
  - rtfm
  - imo
  - fwiw
