name: 'Run sonar analysis'
description: 'Run sonar analysis on a PR or branch'

inputs:
  access-token:
    description: 'Service account access token that allows publishing packages'
    required: true
  username:
    description: 'Service account username that allows publishing packages'
    required: true
  version-code:
    description: 'Version code'
    required: true
  version-name:
    description: 'Version name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Sonarqube PR Analysis
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./gradlew sonar \
          -Dsonar.pullrequest.base=develop \
          -Dsonar.pullrequest.branch=${{ github.head_ref || github.ref_name }} \
          -Dsonar.pullrequest.key=${{ github.event.number }} \
          -PversionCode=$INPUT_VERSION_CODE \
          -PversionName=$INPUT_VERSION_NAME
      shell: bash
      env:
        CI: true
        TOKEN: ${{ inputs.access-token }}
        USERNAME: ${{ inputs.username }}
        INPUT_VERSION_CODE: ${{ inputs.version-code }}
        INPUT_VERSION_NAME: ${{ inputs.version-name }}

    - name: Run Sonarqube Branch Analysis
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        ./gradlew sonar \
          -Dsonar.branch.name=${{ github.head_ref || github.ref_name }} \
          -PversionCode=$INPUT_VERSION_CODE \
          -PversionName=$INPUT_VERSION_NAME
      shell: bash
      env:
        CI: true
        TOKEN: ${{ inputs.access-token }}
        USERNAME: ${{ inputs.username }}
        INPUT_VERSION_CODE: ${{ inputs.version-code }}
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
