name: 'Run gradle check'
description: 'Run the "check" command for a Gradle project'

inputs:
  access-token:
    description: 'Service account access token that allows publishing packages'
    required: true
  username:
    description: 'Service account username that allows publishing packages'
    required: true
  version-code:
    description: 'Version code'
    required: true
  version-name:
    description: 'Version name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Gradle Check
      shell: bash
      run: |
        ./gradlew \
          check \
          -PversionCode=$INPUT_VERSION_CODE \
          -PversionName=$INPUT_VERSION_NAME \
          --stacktrace
      env:
        CI: 'true'
        INPUT_VERSION_CODE: ${{ inputs.version-code }}
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
        TOKEN: ${{ inputs.access-token }}
        USERNAME: ${{ inputs.username }}
