name: 'Detect OS'
description: 'Determines wether the current runner is OSx or *nix'

runs:
  using: "composite"
  steps:
    - name: Detect OS
      id: detectOs
      run: |
        unameS="$(uname -s)"
        case "${unameS}" in
          Linux*)     machine=Linux;;
          Darwin*)    machine=Mac;;
          *)          machine="UNKNOWN:${unameS}"
        esac
        echo "OS_IN_USE=$machine" >> $GITHUB_ENV
        unameM="$(uname -m)"
        echo "ARCH_IN_USE=$unameM" >> $GITHUB_ENV
      shell: bash
