name: 'Detect OS'
description: 'Determines whether the current runner is OSx or *nix'

outputs:
  arch-in-use:
    description: 'The architecture currently in use'
  os-in-use:
    description: 'The OS currently in use'

runs:
  using: "composite"
  steps:
    - name: Detect OS
      id: detectOs
      run: |
        unameS="$(uname -s)"
        case "${unameS}" in
          Linux*)     machine=Linux;;
          Darwin*)    machine=Mac;;
          *)          machine="UNKNOWN:${unameS}"
        esac
        unameM="$(uname -m)"
        echo "OS_IN_USE: $machine"
        echo "os-in-use=$machine" >> $GITHUB_OUTPUT
        echo "ARCH_IN_USE: $unameM"
        echo "arch-in-use=$unameM" >> $GITHUB_OUTPUT
      shell: bash
