name: 'Detect OS'
description: 'Determines wether the current runner is OSx or *nix'

runs:
  using: "composite"
  steps:
    - name: Detect OS
      id: detectOs
      run: |
        unameOut="$(uname -s)"
        echo $unameOut
        case "${unameOut}" in
          Linux*)     machine=Linux;;
          Darwin*)    machine=Mac;;
          *)          machine="UNKNOWN:${unameOut}"
        esac
        echo "OS_IN_USE=$machine" >> $GITHUB_ENV
      shell: bash
