name: 'Update fastlane'
description: 'Updates fastlane'

runs:
  using: "composite"
  steps:
    - name: Update fastlane
      run: |
        export LC_ALL=en_GB.UTF-8
        export LANG=en_GB.UTF-8
        export GEM_HOME=$HOME/.gem
        export GEM_PATH=$HOME/.gem
        
        bundle update fastlane
