name: 'Update fastlane'
description: 'Updates fastlane'

runs:
  using: "composite"
  steps:
    - name: Update fastlane
      run: |
        export LC_ALL=en_GB.UTF-8
        export LANG=en_GB.UTF-8
        export GEM_HOME=$HOME/.gem
        export GEM_PATH=$HOME/.gem
        eval "$(rbenv init - bash)"
        
        gem install bundler:2.4.7
        
        bundle install
        
        bundle update fastlane
      shell: bash
