name: 'Pact broker check'
description: 'Uploads the pact file to the broker'

inputs:
  pact-file-path:
    description: 'Path of the json Pact file'
    required: true
  version-name:
    description: 'Version name'
    required: true
  pact-broker-username:
      description: 'pact username'
      required: true
  pact-broker-password:
      description: 'pact password'
      required: true
  pact-broker-secret:
      description: 'pact secret'
      required: true

runs:
  using: "composite"
  steps:
    - uses: docker://pactfoundation/pact-cli:latest
    - name: Pact file upload
      shell: sh
      run: |
        echo "Uploading file to pact server"
        cat $PACT_FILE_PATH
#        pact-broker help
#        pact-broker publish $PACT_FILE_PATH --consumer-app-version $INPUT_VERSION_NAME
      env:
        CI: 'true'
        PACT_FILE_PATH: ${{ inputs.pact-file-path }}
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
        PACT_BROKER_USERNAME: ${{ inputs.pact-broker-username }}
        PACT_BROKER_PASSWORD: ${{ inputs.pact-broker-password }}
        PACT_BROKER_SOURCE_SECRET: ${{ inputs.pact-broker-secret }}
        PACT_BROKER_BASE_URL: "http://pactbroker-onelogin.staging.account.gov.uk"
