name: 'Setup Runner'
description: 'Set up GitHub Runner environment for building the Android OneLogin app'
inputs:
  JDK-Version:  # id of input
    description: 'The Java Development Kit (JDK) version to use'
    required: true
    default: '17'
  Gradle-Version:
    description: 'The version of gradle for the "gradle/gradle-build-action" step.'
    required: true
    default: 'wrapper'
runs:
  using: "composite"
  steps:
    - name: Add path globally
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.JDK-Version }}

    - name: Add JAVA_HOME globally
      env:
        JDK_VERSION: ${{ inputs.JDK-Version }}
      run: |
        echo "JAVA_HOME=$(/usr/libexec/java_home -v ${JDK_VERSION})" >> $GITHUB_ENV
      shell: bash

    - name: Install snap dependencies
      run: |
        snap install vale --edge
      shell: bash

    - name: Install Dependencies
      run: |
        sudo apt-get install \
          bridge-utils \
          libvirt-clients \
          libvirt-daemon-system \
          qemu-kvm
      shell: bash

    - name: Setup Gradle
      id: setupGradle
      uses: gradle/gradle-build-action@v2
      env:
        CI: 'true'
      with:
        gradle-version: ${{ inputs.gradle-version }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
