name: 'Setup Runner'
description: 'Set up GitHub Runner environment for building the Android OneLogin app'
inputs:
  JDK-Version:  # id of input
    description: 'The Java Development Kit (JDK) version to use'
    required: true
    default: '17'
  Gradle-Version:
    description: 'The version of gradle for the "gradle/gradle-build-action" step.'
    required: true
    default: 'wrapper'
runs:
  using: "composite"
  steps:
    - name: Add path globally
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Add JAVA_HOME globally
      env:
        JDK_VERSION: ${{ inputs.JDK-Version }}
      run: |
        echo "JAVA_HOME=$(/usr/libexec/java_home -v ${JDK_VERSION})" >> $GITHUB_ENV
      shell: bash

    - name: Install KVM hardware acceleration
      run: sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
      shell: bash

    - name: Setup Gradle
      id: setupGradle
      uses: gradle/gradle-build-action@v2
      env:
        CI: 'true'
      with:
        gradle-version: ${{ inputs.gradle-version }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Verify hardware acceleration
      run: emulator -accel-check
      shell: bash

    - name: Store GitHub actions ENV from AWS SecretManager
      id: secrets
      uses: say8425/aws-secrets-manager-actions@v2
      with:
        AWS_DEFAULT_REGION: 'eu-west-2'
        SECRET_NAME: 'di-ipv-dca-mob-android/github-actions-env'
