name: 'Upload to play store'
description: 'Uploads the supplied abbs to the Google Play Store'

inputs:
  abb-paths:
    description: 'App bundle paths to upload, JSON object'
    required: false
    default: 'production'
  package-name:
    description: 'App package name'
    required: false
    default: 'uk.gov.onelogin'

runs:
  using: "composite"
  steps:
    - name: Upload to play store
      run: |
        BUNDLES=($(echo $INPUT_ABB_PATHS | tr ";" "\n"))
        
        for BUNDLE in ${FLAVORS[@]}
        do
          IFS=- read -r FLAVOR ABB_PATH <<< $BUNDLE
        
          case $FLAVOR in
            production*) PACKAGE_NAME=$INPUT_PACKAGE_NAME;;
            *) PACKAGE_NAME=${INPUT_PACKAGE_NAME}.${$FLAVOR};;
          esac
        
          bundle exec fastlane supply --package_name "${PACKAGE_NAME}" --json_key_data "${json_key_data}" --aab ${ABB_PATH} --track internal
        done
      shell: bash
