name: On Branch Push (non-develop/release/main)

on:
  push:
    branches:
      - "**"
      - "!develop"
      - "!release/**"
      - "!main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushJob:
    name: Verify code base when pushed
    runs-on: ubuntu-latest
#    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read
    steps:
      - name: Run checkout github action
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner
#[TBR
      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}
# TBR]
      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./config/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
#          to be removed from here
      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test-managed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-tag }}-${{ steps.version-code.outputs.version-code }}"

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Bundle release
        id: bundle-release
        uses: ./config/actions/gradle-assemble-and-bundle
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flavors: 'build,staging'
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Upload to play store
        uses: ./config/actions/upload-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}
#to be removed up to here
      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
