name: On Branch Push (non-develop/main)

on:
  push:
    branches:
      - "**"
      - "!develop"
      - "!main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushJob:
    name: Verify code base when pushed
    runs-on: macos-latest
#    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    steps:
      - name: Run checkout github action
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Detect OS
        uses: ./config/actions/detect-os

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
