name: On Branch Push (develop)

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushDevelopJob:
    name: Verify code base when pushed
    runs-on: macos-latest
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    steps:
      - name: Run checkout github action
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Bundle release
        id: bundle-release
        uses: ./config/actions/gradle-assemble-and-bundle
        with:
          flavors: 'build,dev,staging,integration'
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-version }}-${{ steps.version-code.outputs.version-code }}"

      - name: Update fastlane
        uses: ./config/actions/update-fastlane

      - name: Upload to play store
        uses: ./config/actions/upload-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}

      - name: Git tag bundles
        uses: ./config/actions/tag-bundles
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}
          version-name: "${{ steps.latest-tag.outputs.current-version }}-${{ steps.version-code.outputs.version-code }}"

      - name: Clean workspace
        if: always()
        uses: ./config/actions/clean-workspace
