name: On Branch Push (non-develop/main)

on:
  push:
    branches:
      - "**"
      - "!develop"
      - "!main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushJob:
    name: Verify code base when pushed
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout github action
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: playstore
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          profile: pixel_7_pro
          disable-linux-hw-accel: false
          script: |
            ./gradlew connectedDebugAndroidTest --continue --stacktrace

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
