name: On Pull Request (develop/release/main)

on:
  pull_request:
    branches:
      - develop
      - main
      - release/*
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPullRequestJob:
    name: Verify code base when pull request is published/updated
    runs-on: macos-latest

    steps:
      - name: Run checkout github action
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-version }}-${{ steps.version-code.outputs.version-code }}"

      - name: Debug arch
        run: |
          echo "Arch is arm64"
        if: ${{ steps.detect-arch.outputs.arch-in-use }} == 'arm64'

      - name: Debug arch
        run: |
          echo "Arch is not arm64 - $ARCH_IN_USE"
        if: ${{ steps.detect-arch.outputs.arch-in-use }} != 'arm64'
        env:
          ARCH_IN_USE: ${{ steps.detect-arch.outputs.arch-in-use }}

      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test
        with:
          architecture: 'arm64-v8a'
          device-profile: 'pixel_xl'
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-version }}-${{ steps.version-code.outputs.version-code }}"
        if: steps.detect-arch.outputs.arch-in-use == 'arm64'

      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-version }}-${{ steps.version-code.outputs.version-code }}"
        if: steps.detect-arch.outputs.arch-in-use != 'arm64'

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
