name: Setup Runner

on:
  workflow_call:
    secrets: inherit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  environment-setup:
    runs-on: ubuntu-latest
    name: Setup Runner
    steps:
      - name: Enable hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Add JAVA_HOME globally
        run: |
          echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          gradle-version: "wrapper"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Store GitHub actions ENV from AWS SecretManager
        id: secrets
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_DEFAULT_REGION: "eu-west-2"
          SECRET_NAME: "di-ipv-dca-mob-android/github-actions-env"
