name: Lint / Unit test codebase

on:
  workflow_call:
    secrets: inherit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    name: Gradle check
    steps:
      - name: Check
        run: |
          ./gradlew check --stacktrace
        env:
          CI: true
