name: Lint / Unit test codebase

on:
  workflow_call:
    secrets: inherit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    name: Generate and Upload build artefacts
    needs: test
    steps:
      - name: Bundle build reports
        if: always()
        run: |
          zip -9 -r reports.zip **/build/reports

      - name: Upload build reports
        id: uploadBuildReports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports
          retention-days: 14
          path: |
            reports.zip
