name: 'Run gradle check'
description: 'Run the "check" command for a Gradle project'

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}
        role-duration-seconds: 1200
        role-skip-session-tagging: true

    - name: Retrieve GitHub actions ENV from AWS SecretManager
      id: secrets
      uses: say8425/aws-secrets-manager-actions@v2
      with:
        AWS_DEFAULT_REGION: "eu-west-2"
        SECRET_NAME: "di-ipv-dca-mob-android/github-actions-env"

    - name: Retrieve Google Play Service ENV from AWS SecretManager
      id: googlePlayServiceSecrets
      uses: say8425/aws-secrets-manager-actions@v2
      with:
        AWS_DEFAULT_REGION: "eu-west-2"
        SECRET_NAME: "di-mobile-android-onelogin-app/github-actions-env"
